### ISSUE TITLE
But there's nothing wrong with R 3.3, right?

### ISSUE THREAD

**Issue by AlexanderPico** [wikipathways/old-rwikipathways#4]
I think that particular BiocCheck warning is a false warning. It implies that R 3.3 is a "dev" version because the second digit is odd. But that's not true. That's a convention for Bioc packages, but not R, right?

I have R 3.3 installed to make sure our packages are compatible with it. I don't think we should bump this to 3.4.

Am I missing something?

https://github.com/wikipathways/rwikipathways/commit/ea6d4b297fe6bee7ddaa34ec949e4accd55da0d1

**Comment by egonw** [comment]
Correct, the 3.4 warning is one made by the BiocCheck package. When we/you submitted the package, we [committed ourselves](https://github.com/Bioconductor/Contributions/issues/687) to comply to their policies. At least some of these have been formalized in that package as checks (so, including the 3.4): "I understand that a minimum requirement for package acceptance is to pass R CMD check and R CMD BiocCheck with no ERROR or WARNINGS."

One of the WARNINGS we promised to not have, is depending on R 3.4...

So far, the only reason why getting it working on 3.3 is actually those ORCIDs... that is, Authors@R seems to have been introduced in 3.4... 

(Think of it as those reviewers/editors demanding no URL references in the bibliography... does not really make sense, but that's just the policies they have in place... and I don't want to risk that we do not get accepted because of something like use wanting 3.3 support too)

**Comment by AlexanderPico** [comment]
It's even worse...

> It is strongly, strongly recommended that all new package depend on the version of R that it will be released under.  New packages currently being accepted will be released under Bioc 3.7 which will be associated with R 3.5.   So as mentioned, eventually users will want to update to use the latest versions anyways.  While new packages could be compatible with earlier versions of Bioc and R releases,  we at Bioconductor cannot guarantee that, which is why we generally insist for consistency sake that the R requirement is the latest version.  R versions can have subtle difference that can have a cascading effect on packages - similarly with packages that are used in dependencies - Since the Bioconductor build system is set up to test under the latest version testing scenario, that is all we can guarantee for compatibility and why we check for this.
